baseURL = "https://lakonethr.github.io/web/"
languageCode = "hr"
defaultContentLanguage = "hr"
title = "lakoNET"

[languages]
  [languages.hr]

  [languages.en]

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_call_box = true
    hide_view_all_services = false  # set to true to hide the View All Services button

  [params.logo]
    mobile = "images/logo/logo-mobile.svg"
    desktop = "images/logo/logo.svg"
    desktop_height = "36px"
    alt = "lakoNET - Vaš Internet"

  [params.homepage_meta_tags]
    meta_description = "lakoNET je revolucionarni distribuirani internet servis koji stavlja korisnika na prvo mjesto."
    meta_og_title = "lakoNET"
    meta_og_type = "website"
    meta_og_url = "https://lakonethr.github.io/web/"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "lakoNET je revolucionarni distribuirani internet servis koji stavlja korisnika na prvo mjesto."
    meta_twitter_card = "summary"
    meta_twitter_site = "@lakonet1"
    meta_twitter_creator = "@lakonet1"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Free Hugo theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Usluge"
    url = "/services/"
      weight = 1

  [[menu.main]]
      name = "Partneri"
      url = "/partners/"
      weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "Glavna"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Kontakt"
    url = "/contact/"
      weight = 2

  [[languages.en.menu.main]]
    name = "Services"
    url = "/en/services/"
      weight = 1

  [[languages.en.menu.main]]
      name = "Partners"
      url = "/en/partners/"
      weight = 2

  # Footer Menu
  [[languages.en.menu.footer]]
    name = "Main"
    url = "/en/"
      weight = 1

  [[languages.en.menu.footer]]
    name = "Contact"
    url = "/en/contact/"
      weight = 2
